try {
    throw Error("Ma premi√®re erreur");
  } catch(e) {
    console.log(e);
  }
  
  
  